<?php

namespace BackendBundle\Repository;

/**
 * VfmonturesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VfmonturesRepository extends \Doctrine\ORM\EntityRepository
{
}
